name: Testing
on: [push]
jobs:
  unit:
    name: build
    env:
      DATABASE_URL: "postgresql://user:password@localhost:5432/visionaria"
      NODE_ENV: test
      NEXTAUTH_SECRET: supersecret
      NEXTAUTH_URL: "http://localhost:3000"
      GOOGLE_CLIENT_ID: GOOGLE_CLIENT_ID
      GOOGLE_CLIENT_SECRET: GOOGLE_CLIENT_SECRET
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@f43a0e5ff2bd294095638e18286ca9a3d1956744 # v3
        with:
          fetch-depth: 0

      - uses: pnpm/action-setup@v2

      - uses: actions/setup-node@1a4442cacd436585916779262731d5b162bc6ec7 # v3
        with:
          node-version: 20.14.0
          cache: "pnpm" # You can active this cache when your repo has a lockfile

      - name: Install deps (with cache)
        run: pnpm install --frozen-lockfile

      - name: Next.js cache
        uses: actions/cache@0c45773b623bea8c8e75f6c82b208c3cf94ea4f9 # v4
        with:
          path: ${{ github.workspace }}/.next/cache
          key: ${{ runner.os }}-${{ hashFiles('**/pnpm-lock.yaml') }}-nextjs

      - run: pnpm tsc

      - run: pnpm lint

      - run: pnpm build
