name: Testing
on: [push]
jobs:
  unit:
    name: build
    env:
      DATABASE_URL: "postgresql://user:password@localhost:5432/visionaria"
      NODE_ENV: test
      NEXTAUTH_SECRET: supersecret
      NEXTAUTH_URL: "http://localhost:3000"
      SUPABASE_URL: "http://127.0.0.1:5432"
      SUPABASE_ANON_KEY: SUPABASE_ANON_KEY
      GOOGLE_CLIENT_ID: GOOGLE_CLIENT_ID
      GOOGLE_CLIENT_SECRET: GOOGLE_CLIENT_SECRET
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: pnpm/action-setup@v2

      - uses: actions/setup-node@v3
        with:
          node-version-file: package.json
          cache: "pnpm" # You can active this cache when your repo has a lockfile

      - name: Install deps (with cache)
        run: pnpm install --frozen-lockfile

      - name: Next.js cache
        uses: actions/cache@v4
        with:
          path: ${{ github.workspace }}/.next/cache
          key: ${{ runner.os }}-${{ hashFiles('**/pnpm-lock.yaml') }}-nextjs

      - run: pnpm tsc

      - run: pnpm lint

      - run: pnpm build
